version: '2.1'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  postgres:
    image: postgres:11
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:5
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
  minio:
    image: minio/minio
    command: server /data
    volumes:
      - ./minio:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: FAKEKEY
      MINIO_SECRET_KEY: FAKESECRET
volumes:
  mysql_data:
    driver: local
  pg_data:
    driver: local
  redis_data:
    driver: local
